plugins {
    alias(libs.plugins.android.application)
}

android {
    namespace 'com.dest4590.sigint'
    compileSdk 36

    defaultConfig {
        applicationId "com.dest4590.sigint"
        minSdk 30
        targetSdk 36
        versionCode 1
        versionName "1.0"

        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }

    buildTypes {
        release {
            minifyEnabled true 
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_11
        targetCompatibility JavaVersion.VERSION_11
    }
    sourceSets {
        main {
            jniLibs.srcDirs = ['src/main/java/com/jniLibs']
        }
    }
}

dependencies {
    implementation libs.appcompat
    implementation libs.material
    implementation libs.constraintlayout
    implementation libs.okhttp
    implementation "androidx.recyclerview:recyclerview:1.4.0"
    implementation files('libs/droidplug-release.aar')
    testImplementation libs.junit
    androidTestImplementation libs.ext.junit
    androidTestImplementation libs.espresso.core
}